name    'zleslie-nsd'
version '0.2.0'
source 'git://github.com/xaque208/puppet-nsd.git'
author 'zleslie'
license 'Apache License Version 2.0'
summary 'A Puppet module to manage NSD'
description 'A module to deploy and manage the NSD authoratative resolver'
project_page 'https://github.com/xaque208/puppet-nsd'
dependency 'puppetlabs/concat', '>= 1.1.0'
